name: Deploy to GitHub Pages
  
on:
  workflow_dispatch:
  push:
    branches: 'main'
  
jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.14
        with:
          architecture: 'x64'  # or: 'x64', 'x86', 'arm32', 'arm64' (or 'aarch64')
          distribution: 'full' # or: 'minimal' (but you probably don't want 'minimal', see note at the bottom of this doc)
          variant: 'CS'        # or: 'BC' for Racket Before Chez
          version: '8.17'      # or: 'stable' for the latest version, 'current' for the latest snapshot, 'pre-release' for the latest pre-release build (defaults to 'stable')

      - run: raco pkg install --auto pollen
      - run: raco pollen render src && raco pollen render src/posts
  
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'src/'
  
  deploy:
    needs: build_site
    runs-on: ubuntu-latest
  
    permissions:
      pages: write
      id-token: write
  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
